### ISSUE TITLE
Allow Multiple (and separate) Scarves Be Worn

### ISSUE THREAD

**Issue by sylv256** [falkreon/Scarves#2]

**Comment by falkreon** [comment]
So as it stands right now, there's really no limit to the amount of scarf attachments an entity can have, or their length, or what supplies them. It's just a matter of the fact that it's based on the IScarfHaver interface, and I'm currently supplying an implementation on ClientPlayers and OtherClientPlayers. Unfortunately, you can only add an interface via mixin once, so I'll have to add more onto the player's impl to cover that use case.

Do you have a vision for how such an API would look to the API consumer?

**Comment by sylv256** [comment]
Unfortunately, I cannot equip more than 1 scarf at a time. It would be cool if I could equip up to a certain amount at a time via trinkets.

**Comment by falkreon** [comment]
Going to close this for now due to end-to-end scarf stapling giving much better versatility. It *would* be nice to accept additional scarves but unfortunately due to the difficulty of accurately placing new attachment points, this is out of scope for now.

In the future: I'd definitely accept a PR to harvest worldspace attachment points from the model - this would have several effects, like potentially better MLP support, and the ability to attach scarves *anywhere*, not just to the neck.

Thanks for the issue!
