### ISSUE TITLE
Compatibility with Create

### ISSUE THREAD

**Issue by Defetyre** [falkreon/Scarves#5]
Can you make it so that an encased fan from Create mod could move scarves?
![2022-10-09_17 39 05](https://user-images.githubusercontent.com/88449275/194752366-f399166c-94be-426a-842e-f6b28a4c328e.png)

**Comment by falkreon** [comment]
Great idea! I'd already thought about doing this with A Fan Of It. More than that, it'd be fun to be walking around, and then see your scarf blowing, and know that it's a good place to put your wind turbines.

Any mod can, already, register a "wind vector provider". If multiple mods register wind providers, both are honored. This is tested and feels great, really adds to the verisimilitude of scarves.

The drawback is that these queries happen at a very high frequency, once per tick per fabric square, so they have to execute *fast*. I'm thinking of having cut-down modes which only query the wind at the ScarfHaver's location or once per second. But I want to leave it to either Create or to other third parties to figure out what the efficient wind provider itself might look like.

If you're a modder and want to make this integration happen yourself, we can definitely speak further on the specifics of this wind API.

**Comment by Defetyre** [comment]
I can't make mods myself just yet. There was a good reason why I turned to you for this feature and not to Create team.
Not sure if you already know it, but there is two teams for Create mod, the one that develops this mod for forge, and one that maintains fabric port of it. I think that because of the fact that your mod is fabric only, it would be inappropriate to ask the main (forge) team to integrate this feature, let alone telling them to design it by themselves. Same partially applies to fabric team, as they usually only fixing fabric specific bugs and port this mod to new versions of minecraft, telling people to leave their content suggestions and non-fabric specific bug reports on forge repo, so they could just pick it up later.

**Comment by falkreon** [comment]
That _is_ a pickle. Obviously since there's no Scarves available for forge, the Create-prime team wouldn't do it, and I'm really impressed by the amount of work the Create-fabric team does already; features not in forge are way out of their scope. I wish I had time to build and maintain a wind provider mod but I very much do not. All I can do is let anyone willing to try know they have my full support.

Thanks for the issue. I'm closing it for now as out of scope, but I really hope we haven't seen the last of this one!
